[package]
name = "carbide"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.20", features = ["derive", "cargo"] }
mlua = { version = "0.10.0", features = ["lua54", "vendored"] }
serde = { version = "1.0.215", features = ["derive"] }
